name: Update RSS from WebDAV

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Cache rclone
      uses: actions/cache@v4
      with:
        path: ~/.local/bin/rclone
        key: rclone-${{ runner.os }}-v1.71.0
        
    - name: Install dependencies
      run: |
        pip install zstandard
        
        if [ ! -f "$HOME/.local/bin/rclone" ]; then
          echo "Installing rclone..."
          mkdir -p ~/.local/bin
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip -q rclone-current-linux-amd64.zip
          cp rclone-*/rclone ~/.local/bin/
          chmod +x ~/.local/bin/rclone
          rm -rf rclone-*
        fi
        
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Configure rclone
      env:
        WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
        WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
        WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
      run: |
        BASE_URL=$(echo "${WEBDAV_URL}" | sed 's|\(https://[^/]*\).*|\1|')
        WEBDAV_PATH=$(echo "${WEBDAV_URL}" | sed 's|https://[^/]*||')
        
        mkdir -p ~/.config/rclone
        cat > ~/.config/rclone/rclone.conf <<EOF
        [webdav]
        type = webdav
        url = ${BASE_URL}
        vendor = other
        user = ${WEBDAV_USER}
        pass = $(rclone obscure ${WEBDAV_PASS})
        EOF
        
        echo "WEBDAV_PATH=${WEBDAV_PATH}" >> $GITHUB_ENV
        
    - name: Sync files from WebDAV
      run: |
        rclone sync webdav:${WEBDAV_PATH}/db_storage ./db_storage --include "*.db"
        
    - name: Run db2rss.py
      run: python db2rss.py
      
    - name: Generate feeds.json
      run: |
        > feeds.json
        
        if [ -d "source_xml" ]; then
          find source_xml -name "*.xml" -type f | sort | while read -r file; do
            filename=$(basename "$file")
            url="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/source_xml/${filename}"
            
            # 读取第4行并提取 CDATA 内容
            title=$(sed -n '4p' "$file" | sed 's/.*<!\[CDATA\[\(.*\)\]\]>.*/\1/')
            
            # 如果没有提取到内容，使用文件名
            if [ -z "$title" ] || [ "$title" = "$(sed -n '4p' "$file")" ]; then
              title="$filename"
            fi
            
            # 转义双引号
            title_escaped=$(echo "$title" | sed 's/"/\\"/g')
            
            echo "{\"name\": \"${title_escaped}\", \"feed\": \"${url}\"}" >> feeds.json
          done
        fi
        
        FEED_COUNT=$(wc -l < feeds.json)
        echo "Generated feeds.json with ${FEED_COUNT} RSS feeds"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add source_xml/ feeds.json
        
        if ! git diff --staged --quiet; then
          git commit -m "Update RSS feeds [skip ci]"
          git push
        fi

